# Generated by Django 4.2.4 on 2023-09-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_borrowing_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='total_borrowing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
